name: Publish Python packages
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml

  publish:
    name: Publish to PyPI
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Checkout micropython-lib submodule
        run: git submodule update --init near_py_tool/assets/micropython/lib/micropython-lib
      - name: Install dependencies
        run: sudo apt install -y make emscripten python3-venv python3-pip python-is-python3
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Build packages
        run: uv build
      - name: Publish the packages
        run: uv publish --token "${{ secrets.NEAR_PY_TOOL_PYPI_TOKEN }}"
