name: Test
on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  tests:
    name: Basic functional test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Checkout micropython-lib submodule
        run: git submodule update --init near_py_tool/assets/micropython/lib/micropython-lib
      - name: Install dependencies
        run: sudo apt install -y make emscripten python3-venv python3-pip python-is-python3
      - name: Install near CLI
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/near/near-cli-rs/releases/download/v0.18.0/near-cli-rs-installer.sh | sh
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Sync the project
        run: uv sync
      - name: Create a new contract project
        run: uv run near-py-tool new test-project
      - name: Build the example contract
        run: uv run near-py-tool build non-reproducible-wasm --project-dir=test-project
      - name: Create a testnet dev account with random id
        run: uv run near-py-tool create-dev-account use-random-account-id autogenerate-new-keypair save-to-legacy-keychain network-config testnet create
      - name: Deploy the example contract to testnet
        run: uv run near-py-tool deploy --project-dir=test-project build-non-reproducible-wasm '*' with-init-call echo json-args '{"input":"ci-test"}' prepaid-gas '300 Tgas' attached-deposit '0 NEAR' network-config testnet sign-with-legacy-keychain send
